version: "3.9"

services:
  debian-11-server-cmake:
    build:
      context: ..
      dockerfile: docker/debian-11-server-cmake/Dockerfile

  debian-11-server-make:
    build:
      context: ..
      dockerfile: docker/debian-11-server-make/Dockerfile

  debian-12-server-cmake:
    build:
      context: ..
      dockerfile: docker/debian-12-server-cmake/Dockerfile

  debian-12-server-make:
    build:
      context: ..
      dockerfile: docker/debian-12-server-make/Dockerfile

  ubuntu-22-server-cmake:
    build:
      context: ..
      dockerfile: docker/ubuntu-22-server-cmake/Dockerfile

  ubuntu-22-server-make:
    build:
      context: ..
      dockerfile: docker/ubuntu-22-server-make/Dockerfile

  ubuntu-24-server-cmake:
    build:
      context: ..
      dockerfile: docker/ubuntu-24-server-cmake/Dockerfile

  ubuntu-24-server-make:
    build:
      context: ..
      dockerfile: docker/ubuntu-24-server-make/Dockerfile

