name: Prepare checkout tools
description: Ensure tar/git/ca-certificates are present in job containers before actions/checkout

runs:
  using: composite
  steps:
    - name: Install checkout prerequisites
      shell: sh
      run: |
        set -eu

        need_install=0
        command -v tar >/dev/null 2>&1 || need_install=1
        command -v git >/dev/null 2>&1 || need_install=1
        command -v update-ca-certificates >/dev/null 2>&1 || need_install=1
        [ "${need_install}" -eq 1 ] || exit 0

        if command -v apt-get >/dev/null 2>&1; then
          apt-get update
          apt-get install -y --no-install-recommends tar git ca-certificates
        elif command -v zypper >/dev/null 2>&1; then
          zypper --non-interactive refresh
          zypper --non-interactive install tar git ca-certificates
        elif command -v apk >/dev/null 2>&1; then
          apk add --no-cache tar git ca-certificates
        elif command -v dnf >/dev/null 2>&1; then
          dnf -y install tar git ca-certificates
        elif command -v yum >/dev/null 2>&1; then
          yum -y install tar git ca-certificates
        elif command -v pacman >/dev/null 2>&1; then
          pacman -Sy --noconfirm archlinux-keyring || true
          pacman -S --noconfirm tar git ca-certificates
        else
          echo "Unsupported package manager for installing checkout tools" >&2
          exit 2
        fi
