#!/usr/bin/env bash
set -euo pipefail

output=""

usage() {
  cat <<'USAGE' >&2
Usage: write-lane-env.sh --output PATH
USAGE
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "${output}" ]]; then
  echo "Missing --output" >&2
  usage
fi

mkdir -p "$(dirname "${output}")"

lane_env_keys=(
  LEGACY_APPLY_OWNERSHIP
  XYMONUSER
  XYMONGROUP
  ENABLE_LDAP
  ENABLE_SNMP
  BUILD_TOOL
  GOAL
  REF_MODE
  PUBLISH
  VARIANT
  BASELINE_ROOT
  REF_OS
  PLATFORM_OS
  OS_VERSION
  ARTIFACT_FAMILY
  PLATFORM_ID
  REF_STAGE_ROOT
  CMAKE_BIN
  PREPARE_PROFILE
  CHECKOUT_MODE
  CONTAINER_IMAGE
  CONTAINER_OPTIONS
  RUNTIME
  GITHUB_ACTIONS
  CI
  GITHUB_WORKSPACE
  GITHUB_REPOSITORY
  GITHUB_SHA
  GITHUB_SERVER_URL
)

{
  echo "#!/usr/bin/env bash"
  echo "# generated by ci/run/ref/write-lane-env.sh"
  for key in "${lane_env_keys[@]}"; do
    if [[ -v "${key}" ]]; then
      printf 'export %s=%q\n' "${key}" "${!key}"
    fi
  done
} > "${output}"

chmod 0600 "${output}"
