#!/usr/bin/env bash
set -euo pipefail

output=""
lane_env_json=""
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat <<'USAGE' >&2
Usage: write-lane-env.sh --output PATH --lane-env-json JSON
USAGE
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      output="${2:-}"
      shift 2
      ;;
    --lane-env-json)
      lane_env_json="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "${output}" ]]; then
  echo "Missing --output" >&2
  usage
fi
if [[ -z "${lane_env_json}" ]]; then
  echo "Missing --lane-env-json" >&2
  usage
fi

mkdir -p "$(dirname "${output}")"

python3 - "${lane_env_json}" "${script_dir}" > "${output}" <<'PY'
import json
import os
import shlex
import sys

sys.path.insert(0, sys.argv[2])
from lane_env_contract import validate_known_lane_env_keys  # noqa: E402


def fail(message: str) -> None:
    raise SystemExit(message)


try:
    payload = json.loads(sys.argv[1])
except Exception as exc:  # pragma: no cover - defensive
    fail(f"Invalid --lane-env-json payload: {exc}")

if not isinstance(payload, dict):
    fail("--lane-env-json must decode to an object")
unknown_keys = validate_known_lane_env_keys(payload)
if unknown_keys:
    fail("--lane-env-json has unknown keys: " + ", ".join(unknown_keys))

print("#!/usr/bin/env bash")
print("# generated by ci/run/ref/write-lane-env.sh")

for key, value in payload.items():
    if not isinstance(key, str) or not key:
        fail("--lane-env-json keys must be non-empty strings")
    if value is None:
        continue
    if not isinstance(value, str):
        value = str(value)
    print(f"export {key}={shlex.quote(value)}")

for key in (
    "GITHUB_ACTIONS",
    "CI",
    "GITHUB_WORKSPACE",
    "GITHUB_REPOSITORY",
    "GITHUB_SHA",
    "GITHUB_SERVER_URL",
    "GITHUB_TOKEN",
):
    value = os.environ.get(key)
    if value is None:
        continue
    print(f"export {key}={shlex.quote(value)}")
PY

chmod 0600 "${output}"
