name: Setup Debian build environment
description: Install Debian/Ubuntu build dependencies

inputs:
  profile:
    required: false
    default: default

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        bash scripts/ci/setup-debian.sh "${{ inputs.profile }}"
