name: Reference Validation - Debian

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-family:
    uses: ./.github/workflows/ref-validate-select.yml
    with:
      family: debian
    secrets: inherit
