name: Reference Generation - OpenBSD

on:
  workflow_dispatch:

jobs:
  ref-make-openbsd:
    name: ${{ matrix.lane.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - lane:
              name: server
              runtime: bsd_vm
              runs_on: ubuntu-22.04
              build_tool: make
              ref_os: openbsd
              os_version: "7.8"
              architecture: x86-64
              vm_memory: 1024M
              vm_cpu_count: 2
              variant: server
          - lane:
              name: client ct-client
              runtime: bsd_vm
              runs_on: ubuntu-22.04
              build_tool: make
              ref_os: openbsd
              os_version: "7.8"
              architecture: x86-64
              vm_memory: 1024M
              vm_cpu_count: 2
              variant: localclient
          - lane:
              name: client ct-server
              runtime: bsd_vm
              runs_on: ubuntu-22.04
              build_tool: make
              ref_os: openbsd
              os_version: "7.8"
              architecture: x86-64
              vm_memory: 1024M
              vm_cpu_count: 2
              variant: client
    uses: ./.github/workflows/ref-make-reusable.yml
    with:
      lane_name: ${{ matrix.lane.name }}
      lane_json: ${{ toJSON(matrix.lane) }}
