name: Reference Validation - RPM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-family:
    uses: ./.github/workflows/ref-validate-select.yml
    with:
      family: rpm
    secrets: inherit
