name: Reference Validation - CentOS 7

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-family:
    uses: ./.github/workflows/ref-validate-select.yml
    with:
      family: centos7
    secrets: inherit
